### ISSUE TITLE
[Dawn] More persistent (saved state) features for menu, editor, files, configurations

### ISSUE THREAD

**Issue by kev-chien** [pioneers/PieCentral#120]
Some nice editor features that shouldn't be too hard to implement
- Have automatic re-opening of last file, e.g. having it saved in persistent local memory
- Have configuration (persistent setting) if students don't necessarily want to see their last file they were working on when they last closed dawn for some reason
- Have menu bar show recently opened files (and easy clicking)
- Have configuration (persistent setting) if for some reason students don't want to be prompted when they close editor without saving that they didn't save

**Comment by kevinmasd** [comment]
I don't know if any of these things are necessary. The saving prompt seems too important to ignore, and automatic re-opening of last file seems odd to me.

**Comment by kev-chien** [comment]
True haha, I think these features may not be something students necessarily want. It may be helpful to survey them midway of what features they think they would want and learn about how they use Dawn.
Otherwise, I'll close the issue for now.
