### ISSUE TITLE
[Dawn] keyboard shortcuts

### ISSUE THREAD

**Issue by kev-chien** [pioneers/PieCentral#121]
Implement keyboard shortcuts for anything useful or that students may want quick access to. Most likely the following features (with rough suggestions for key bindings)
Note: Super refers to Cmd on Mac, Control on Windows

Robot
- Change IP (Super I)
- Upload (Super U)
- Run (Super Y) _(Super+R is used to refresh app, maybe change to be Super Shift R)_
- Stop (Super W)
- E-Stop (Super E)

Editor
- Increase font size (Super +)
- Decrease font size (Super -)

Misc
- Open Preferences/Config (Super ,)
- Open API (Super P)

**Comment by kevinmasd** [comment]
End of 2018 Season. If issue re-arises, create a new issue.
