### ISSUE TITLE
Make sure that runtime updates do not override student code

### ISSUE THREAD

**Issue by nikitakit** [pioneers/PieCentral#208]
Currently runtime updates are formed by copying the `runtime` folder into a zip archive. Then the installation will unzip that folder. The previous runtime folder is deleted in the process now.

As it stands, this will probably delete any student code and replace it with the testing file that's in the repo. Some more sensible behavior should happen instead

**Comment by jonathan-j-lee** [comment]
This should now be resolved [here](https://github.com/pioneers/PieCentral/commit/86c75bf3170f3f5894024e0e7945eb3b6053d173).
