### ISSUE TITLE
[RUNTIME] Validate error handling on unparsable student code

### ISSUE THREAD

**Issue by nikitakit** [pioneers/PieCentral#267]
If the student code has an error such that the entire file can't be parsed (e.g. missing parentheses, bad indentation, etc.), I'm not sure that a meaningful error message is reported to Dawn.

One team had this issue, and I believe all Dawn did was switch back into the idle state.

**Comment by baby-bell** [comment]
This still happens. I think we just need to catch `SyntaxError`

**Comment by baby-bell** [comment]
Closed by #567
