### ISSUE TITLE
[DAWN]  Console scrolls from top, not bottom.

### ISSUE THREAD

**Issue by dHutchings** [pioneers/PieCentral#278]
If a robot spams print statements, the text box expands to the bottom.  This means that the print statement that is viewed from the text box is only the _first_ one.

This should be changed, so that the most recent print statement is shown, i.e. more like a standard terminal.

**Comment by kevinji** [comment]
[Keep overflow div scrolled to bottom unless user scrolls up](https://stackoverflow.com/questions/18614301/keep-overflow-div-scrolled-to-bottom-unless-user-scrolls-up) looks like it'd be helpful. It should be easier since we can control when input comes in, so no timer should be necessary.

**Comment by kevinmasd** [comment]
Handling in #281
