### ISSUE TITLE
[Hibike] Setup and Flashing 

### ISSUE THREAD

**Issue by ArjunSridhar1** [pioneers/PieCentral#285]
- setup.py not compatible with anaconda
- pyserial may have new verision
- lots of things not working on Arjun's computer

**Comment by baby-bell** [comment]
Willing to help new people with this

**Comment by renegamino012** [comment]
@ArjunSridhar1 Can you try these setup scripts, send some error screenshots? The branch name is "hibike/setup."

**Comment by ArjunSridhar1** [comment]
Sure, I probably won't get a chance to do this until fall comp.

**Comment by tingtingchiang** [comment]
Going to assume scripts are working now. We can reopen with the error(s) if they come up again.
