### ISSUE TITLE
[DAWN] Runtime-Side State Information Display in Dawn

### ISSUE THREAD

**Issue by dHutchings** [pioneers/PieCentral#297]
Hi.

There's currently no visual feedback of any kind showing what the "Robot state" is.  Is the robot disable?  In teleop?  In autonomous?  Currently, there's no way to tell at a glance.

I understand that making the drop-down menu explicitly change is hard, so maybe that's not the best way forward.  But could we at least have an indicator, something like the battery voltage indicator?  It'd be better than exactly nothing.

Thank you!

**Comment by kevinmasd** [comment]
Dawn displays what it sends according to #274 . As for what Runtime is sending back to Dawn, this isn't addressed but can be done since the state does hold this information.
