### ISSUE TITLE
Dawn Auto / Tele-op Confusion

### ISSUE THREAD

**Issue by scottnuma** [pioneers/PieCentral#306]
One of the mentors contacted EDU for instructions on how to run autonomous mode.
I've also seen some staff mess up when trying to run tele-op instead of autonomous.

To provide more clarity, what if the mode button was moved to the immediate right of the play button and reduced to just a sliver drop down? This would essentially be like an option button for the play button.

**Comment by kevinmasd** [comment]
That is what it looks like in the development branches. I'll release a version of Dawn with the functionality later today.

**Comment by scottnuma** [comment]
Ah super - thanks

**Comment by kevinmasd** [comment]
Wait for #316 to go through
