### ISSUE TITLE
[HIBIKE] Clean up reset.py and __init__.py

### ISSUE THREAD

**Issue by brandonxxlee** [pioneers/PieCentral#337]
reset.py - legacy code for a quirky bootloader when we made our own smartsensors. Currently this is redundantly called 3 times every time we run flash.sh. Make sure to remove the relevant lines from flash.sh as well.

__init__.py - why does this import hibike_simulator.py? I don't see this anywhere in piecentral

**Comment by tingtingchiang** [comment]
Fixed
