### ISSUE TITLE
Dawn Debug Mode

### ISSUE THREAD

**Issue by AllanYangZhou** [pioneers/PieCentral#35]
This is unnecessary for productions, it is only used in development. See this for ideas: https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds. We already have a `process.env.NODE_ENV`, so you can check if that variable is equal to `'development`'.

**Comment by kevinmasd** [comment]
Going to expand on this. Various features (Fake Runtime, SFTP logging) seem to only be useful for Devs. Perhaps logging them onto a file or keeping debug flags may be useful.
