### ISSUE TITLE
[HIBIKE] Yogi Bear Error State Handling

### ISSUE THREAD

**Issue by brandonxxlee** [pioneers/PieCentral#374]
Change the Enable pin on Motor controller to go to an ADC pin. Ask Electrical for what pin it goes to. 

The Enable pin is an analog value that can be read based on what state the driver is in. Usually, it is around 5V, but when the motor controller falls into an error state, it will fall to roughly 4.5 volts. This can be read on an ADC pin, and the error state can be either handled in some way, i.e. displaying on Dawn if a motor controller status.

- [x] Switching Enable pin from Digital to Analog
- [x] Change Enable pin to read from different pin (enablepin = 21, enableAnalog=A3)
- [x] Check for Error state
- [x] Handle response to Error State
- [x] Check if code works

**Comment by tingtingchiang** [comment]
Switch pin to read as analog and giving it an error state.

**Comment by baby-bell** [comment]
This requires some board changes as well, so probably will not happen. Postponed until next year.
