### ISSUE TITLE
[HIBIKE] add a --help flag to ./flash.sh that prints the device names

### ISSUE THREAD

**Issue by viviehn** [pioneers/PieCentral#391]
Because it's bothersome when you forget what they are, and it would be nice to not have to return to the README every time you forget

**Comment by dHutchings** [comment]
Last year, I got so fed up with hibike's flash script that I implemented tab-completion:

https://github.com/pioneers/PieCentral/pull/182

Just mash tab & it'll tell you the options.  Works on ubuntu, should work on arch (for seiya et al) (but I can't recall if it did or not).  You'd have to re-run the install script, if you last ran it before March 3 2017.

Should be quite easy to add a -h option to the flashing script, and have it give you the output of ./utils/device_names.sh

**Comment by baby-bell** [comment]
Should be addressed by #393
