### ISSUE TITLE
[HIBIKE] Add `timestamp` debug command to hibike/runtime

### ISSUE THREAD

**Issue by baby-bell** [pioneers/PieCentral#395]
Currently, there is nothing in the way of time information for Hibike and Runtime commands. This greatly increases the pain involved in measuring latency. It would be nice if there was a command to print timestamps at every level.

**Comment by baby-bell** [comment]
# Timestamp Spec
There are changes that should be made at every level of the stack, but they are mostly simple.

1. Runtime receives the `timestamp` command from Dawn. It attaches the current time,
and sends the packet data along to StateManager. 
This should modify the `runtime` function.
New commands should also be added to `runtimeUtil.py`.
2.  StateManager receives the command from runtime and invokes the function associated
with the command. It adds its own timestamp and passes the packet along to Hibike.
This would involve the addition of a method to StateManager, along with alteration of its
mapping dictionary.

**Comment by tingtingchiang** [comment]
3. Hibike will receive this command from StateManager and process it in an if/elif/else block that can be found by ctl+f "enumerate_all" (another command sent from StateManager). 
We should figure out how to return the information, either through another message packet/pipe or as another "device". I'm personally for device

**Comment by baby-bell** [comment]
The chain goes in reverse, we send back to state manager through a pipe. We should have two types of commands, to indicate whether it's coming from StateManager or Dawn.

**Comment by baby-bell** [comment]
Implemented in #430
