### ISSUE TITLE
[RUNTIME] Gampad error when running autonomous code

### ISSUE THREAD

**Issue by ArjunSridhar1** [pioneers/PieCentral#419]
Runtime throws a gamepad not connected error when you try to run autonomous code on a robot. You should be able to run autonomous code on a robot without a gamepad connected to your laptop.

**Comment by tingtingchiang** [comment]
Is Dawn sending Gamepad information when in autonomous?

**Comment by ArjunSridhar1** [comment]
No, you can't run autonomous code unless you connect a controller. We don't have a controller connected so we don't send any info.

**Comment by baby-bell** [comment]
Could not reproduce, (un?)fortunately. I'm closing this for now, but feel free to reopen if the issue comes back.
