### ISSUE TITLE
[HIBIKE/RUNTIME] Identify major sources of latency by running tests

### ISSUE THREAD

**Issue by baby-bell** [pioneers/PieCentral#428]
Once timestamps are implemented, we should run Hibike and Runtime with mutliple devices to figure out where the most lag is coming from

**Comment by baby-bell** [comment]
Currently blocked on networking

**Comment by tingtingchiang** [comment]
We've gotten the data we need. 
The major area causing latency is from Dawn to the robot, which we can't exactly fix.
We'll revisit the tests after we start async i/o
