### ISSUE TITLE
Dawn/Runtime Release Version Number

### ISSUE THREAD

**Issue by ArjunSridhar1** [pioneers/PieCentral#436]
The Dawn release version number should be v8.0 or v18.0 to correspond to the year. We should remove the leading 0.
Runtime should incorporate this versioning scheme as well.

**Comment by ArjunSridhar1** [comment]
The field control version number should also match the regular version of dawn. 
- A concerned mentor wondered why FC version was 3.

**Comment by kevinmasd** [comment]
Handling in #506
