### ISSUE TITLE
[RUNTIME] Sending codes from field control to robots

### ISSUE THREAD

**Issue by JHGZhou** [pioneers/PieCentral#440]
For this years game, we need to send codes we generate to each of the robots. We might have to make it a method call or something similar, but in the end they need to be able to receive this code from field control when they want it.

**Comment by baby-bell** [comment]
There are three things that need to be done:
- [x] Add storage space for the code to StateManager
- [x] Change Ansible protobufs (maybe) to account for this
- [x] Add an API call for students

**Comment by baby-bell** [comment]
Addressed by #449
