### ISSUE TITLE
[RUNTIME/EDU] Refine the design of the student API

### ISSUE THREAD

**Issue by baby-bell** [pioneers/PieCentral#444]
It's a good idea to think about the design of the student API, and perhaps refine it. This is heavily related to EDU, and it should be a collaborative effort.

**Comment by tingtingchiang** [comment]
Example Code found here: https://pioneers.berkeley.edu/software/robot_api#example-code
should be changed to make more sense when run as is. (thresholds make it so the motors can go from 0-100% very quickly.

Other changes can be found here: https://docs.google.com/document/d/1iMge74Jf0-_6HtJmM_fDnCNQEv-vhfEKCdAEnax11I8/edit (Sign in with your pioneers account to see it)

**Comment by baby-bell** [comment]
Closed by #471
