### ISSUE TITLE
[HIBIKE] Use `asyncio`

### ISSUE THREAD

**Issue by baby-bell** [pioneers/PieCentral#446]
Realistically, the way HIbike does IO right now would be better suited for async io. This is super far off in the future probably.

**Comment by karthik-shanmugam** [comment]
Is it possible to convert parts of hibike to asyncio while keeping the rest synchronous and threaded?

**Comment by baby-bell** [comment]
It's difficult, because HIbike is built on the assumption that threads are being used. There are a bunch of
explicit event loops that would need to be converted to coroutines.

**Comment by tingtingchiang** [comment]
let's use hibike/asyncio as master branch for any changes.

**Comment by tingtingchiang** [comment]
- [ ] Transport write methods (through coroutine)
- [ ] Read (can be overwritten)
- [ ] Asyncio and pipe interface (read and write from hibike to sm)
- [ ] Integrate hotplugging into async
- [ ] How to keep coroutines running in the loop as a loop (while true + await)
- [ ] How to stop looping coroutines from running again
- [ ] Exceptions behavior
