### ISSUE TITLE
Replace CPython with PyPy

### ISSUE THREAD

**Issue by jonathan-j-lee** [pioneers/PieCentral#476]

**Comment by baby-bell** [comment]
Thanks Jonathan. [Download link](http://pypy.org/download.html#default-with-a-jit-compiler)

**Comment by baby-bell** [comment]
Unfortunately this may take some time. The `softfloat` build for ubuntu doesn't actually work on the BB, and the hardfloat version only works for Raspbian. We might consider building it ourselves, somehow.
See the `devops/pypy-build-script` branch.

**Comment by baby-bell** [comment]
After some testing, it appears that pypy is actually quite memory intensive, and OOMs quickly on the BBB. I suspect this is because of the JIT. Unfortunately, it is not very fast either.
