### ISSUE TITLE
Travis CI GitHub Apps migration

### ISSUE THREAD

**Issue by jonathan-j-lee** [pioneers/PieCentral#612]
GitHub Services, which is how Travis currently builds PiE repos, will be [discontinued after next January](https://developer.github.com/changes/2018-04-25-github-services-deprecation/#deprecation-timeline). GitHub Apps replaces GitHub Services. Travis CI is also taking this opportunity to move existing open-source projects (like PieCentral) to [`travis-ci.com`](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) from `travis-ci.org`.

I've installed the Travis CI GitHub App with read permissions for `PieCentral`, `website`, and `pimulator` through Marketplace. If I've understood the timeline correctly, we should be able to migrate the repositories soon on Travis, since I've just activated the `pioneers` organization on `travis-ci.com`.

**Comment by nikitakit** [comment]
Thanks for keeping me in the loop about the upcoming changes! Let me know if you need any help or additional privileges.

**Comment by jonathan-j-lee** [comment]
> Open source projects and their build history will continue to run on `travis-ci.org` at this time.

It seems like Travis has pushed back their migration date back several times, and running existing open-source projects on `travis-ci.com` has become an opt-in process. The Travis CI GitHub app continues to build our projects as things are, so I will close this issue for now. Nevertheless, we should continue watching for announcements.
