### ISSUE TITLE
[DAWN] Shepherd Integration

### ISSUE THREAD

**Issue by ewc340** [pioneers/PieCentral#644]
- Designate master robot from each alliance through team number (represented by last 2 digits of a robot's ip address)

**Comment by lawrencechen14** [comment]
Task has been completed up to specification and has passed our fake Shepherd tests. Now just waiting for Shepherd to finalize dawn_server communications before pushing to master.

**Comment by ewc340** [comment]
Issue should be fixed with PR #687
