### ISSUE TITLE
Add Protobuf compilers onto beaglebones

### ISSUE THREAD

**Issue by brandonxxlee** [pioneers/PieCentral#80]
We currently are committing compiled protobufs into the main repo. These should be instead placed in the gitignore, once we are able to compile the files on the beaglebone.

**Comment by nikitakit** [comment]
The devops scripts now handle compiling the protobufs and packaging them into the update tarball. Now that #131 is merged these scripts are run by travis for git tags, uploading the tarballs to github.

There should no longer be a need to put protobuf compilers on the beaglebones. It is also now safe to remove the compiled protos from the repo, except that it should be scheduled to avoid breaking people's development flow.

**Comment by nikitakit** [comment]
Closing because travis now takes care of protobuf compilation.
