### ISSUE TITLE
Dawn tabs for multiple files

### ISSUE THREAD

**Issue by kev-chien** [pioneers/PieCentral#94]
Currently students can only view and edit one file. In addition, new file erases the current code, so could create a new tab instead.

UI could utilize [bootstrap navs](https://react-bootstrap.github.io/components.html#navigation)

Or, use [electron-windows](https://github.com/jprichardson/electron-window) but considering gamepads and peripherals this could be clunky. Maybe main window will show peripherals/gamepads and other windows just the code editor.

**Comment by kev-chien** [comment]
https://www.npmjs.com/package/electron-tabs is an npm package that gets the job done.

**Comment by kevinmasd** [comment]
End of 2018 Season. If issue re-arises, create a new issue.
