### ISSUE TITLE
Hosted student API documentation

### ISSUE THREAD

**Issue by nikitakit** [pioneers/PieCentral#96]
We previously had student API documentation autogenerated from docstrings using sphinx, and hosted [on readthedocs](http://pie-api.readthedocs.io/). It would be nice to do something similar this year.

I am one of several admins for our readthedocs account/subdomain, and can help if you want to reuse that website.

**Comment by kevinmasd** [comment]
We could also package the documentation into Dawn; Dawn already tries to get documentation (though it didn't work last time due to networking).

**Comment by jiangdaniel** [comment]
If we put the [API on discourse](https://discourse.pierobotics.org/t/api-spec/281), do we still have to host it on readthedocs too?

**Comment by kevinji** [comment]
readthedocs (arguably) has a better interface for searching through the docs, so I'd personally say it's useful.

**Comment by jiangdaniel** [comment]
Our API is pretty short this year though, so it might not be that big of a deal?  And it's a little bit easier for us to maintain a single copy of the API rather than several copies.

**Comment by nikitakit** [comment]
We put an authoritative copy of the API docs up on our website, so I'm now closing this issue.
